n = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(n.__class__))
print('Só tem espacos? {}'.format(n.isspace()))
print('É um numero? {}'.format(n.isnumeric()))
print('É alfabetico? {}'.format(n.isalpha()))
print('É alfanumerico? {}'.format(n.isalnum()))
print('Está em maiúsculas? {}'.format(n.isupper()))
print('Está em minuscula? {}'.format(n.islower()))
print('Está capitalizada? {}'.format(n.isprintable()))